### ISSUE TITLE
[GTK] Exception thrown on MessageBox.Show

### ISSUE THREAD

**Issue by SlowLogicBoy** [picoe/Eto#1004]
## Expected Behavior
Message shown with msg

## Actual Behavior
```
   "System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at GLib.Marshaller.StringFormat(String format, Object[] args)
   at Gtk.MessageDialog..ctor(Window parent_window, DialogFlags flags, MessageType type, ButtonsType bt, Boolean use_markup, String format, Object[] args)
   at Eto.GtkSharp.Forms.MessageBoxHandler.ShowDialog(Control parent)
   at Eto.Forms.MessageBox.Show(String text, MessageBoxType type)
   at Submission#0.<<Initialize>>b__0_0(Object s, EventArgs e) in Path\To\My\Project\Test.csx:line 22"
```
Exception thrown.

## Steps to Reproduce the Problem

  1. Run code below
  2. Click on a button

## Code that Demonstrates the Problem

```csharp
#! "netcoreapp2.0"

#r "nuget: Eto.Platform.Gtk, 2.4.0-*"

using Eto.Forms;

var msg = @"System.NotSupportedException: Specified method is not supported.
   at Task<long> Submission#0+Repository.CountAsync(ICommandOptions options) in Path\To\My\Project\Repositories\Repository.csx:line 75
   at void Castle.Proxies.Invocations.IReadOnlyRepository`1_CountAsync.InvokeMethodOnTarget()
   at void Castle.DynamicProxy.AbstractInvocation.Proceed()
   at void Submission#0+LoggingInterceptor.Intercept(IInvocation invocation) in Path\To\My\Project\Framework\Interceptors\LoggingInterceptor.csx:line 26
   at void Castle.DynamicProxy.AbstractInvocation.Proceed()
   at void Submission#0+GuardInterceptor.Intercept(IInvocation invocation) in Path\To\My\Project\Framework\Interceptors\GuardInterceptor.csx:line 27
   at void Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Task<long> Castle.Proxies.IRepository.CountAsync(ICommandOptions options)
   at void Submission#0+ReadOnlyRepositoryViewModel<T>.Count(object sender, EventArgs args)+() => { } [0] in Path\To\My\Project\GUI\ViewModels\ReadOnlyRepositoryViewModel.csx:line 49
   at void Submission#0+ReadOnlyRepositoryViewModel<T>.Try(Action action) in Path\To\My\Project\GUI\ViewModels\ReadOnlyRepositoryViewModel.csx:line 38";

var app = new Application(new Eto.GtkSharp.Platform());
app.Run(new Form{
    Title = "Hello",
    Content = new Button((s, e) => MessageBox.Show(msg, MessageBoxType.Error))
});
```

## Specifications

  - Version: 2.4.0-build1295
  - Platform(s): Gtk3 (on Windows 10 x64 and Linux x64)

**Comment by SlowLogicBoy** [comment]
Tested. Fixed by #1005.
