### ISSUE TITLE
[GTK]new Bitmap(string fileName) Exception

### ISSUE THREAD

**Issue by SlowLogicBoy** [picoe/Eto#1082]
## Expected Behavior
Bitmap loaded.

## Actual Behavior
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Gdk.Pixbuf..ctor(String filename)
   at Eto.GtkSharp.Drawing.BitmapHandler.Create(String fileName)
   at Eto.Drawing.Bitmap..ctor(String fileName)
   at Submission#0.<<Initialize>>d__0.MoveNext() in d:\Code\Git\dnScripts\Scripts\Test.csx:line 7
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
```

## Steps to Reproduce the Problem

  1. Run provided code

## Code that Demonstrates the Problem

```csharp
#r "nuget: Eto.Platform.Gtk, 2.4.1"

using Eto.Drawing;
using Eto.Forms;

var app = new Application(new Eto.GtkSharp.Platform());
var bitmap = new Bitmap("Logo.png"); //Path.GetFullPath("Logo.png") //This also doesn't work.
```

## Workaround
```csharp
var app = new Application(new Eto.GtkSharp.Platform());
using(var stream = File.OpenRead("Logo.png"))
   var bitmap = new Bitmap(stream);
```
## Specifications

  - Version: 2.4.1
  - Platform(s): GTK3 (Eto.Platform.Gtk) On Windows (I might be using outdated GTK package), I can't reproduce this on Linux.

**Comment by SlowLogicBoy** [comment]
Upgrading GTK in windows solved the problem
