### ISSUE TITLE
Could not detect platform on dotnet core

### ISSUE THREAD

**Issue by trampster** [picoe/Eto#1305]
According to https://github.com/picoe/Eto/pull/953 dotnet core is supported with a GTK3 backend. However when I try to use it from dotnet core on linux I get the following while running dotnet run:

## Expected Behavior
When running from dotnet core 2.1 with the GTK3 backend the UI is shown

## Actual Behavior

```
/home/daniel/Work/ropu/ClientUI/ClientUI.csproj : warning NU1701: Package 'Eto.Platform.Gtk3 2.4.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
/home/daniel/Work/ropu/ClientUI/ClientUI.csproj : warning NU1701: Package 'Eto.Platform.Gtk3 2.4.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.

Unhandled Exception: System.InvalidOperationException: Could not detect platform. Are you missing a platform assembly?
   at Eto.Platform.get_Detect()
   at Eto.Forms.Application..ctor()
   at ClientUI.MyForm.Main() in /home/daniel/Work/ropu/ClientUI/Program.cs:line 20
```

## Steps to Reproduce the Problem

  1. Create new project using: dotnet new console
  2. Copy paste the UI code from the project readme into program.cs
  3. Add the following package references to the .csproj file

```
    <PackageReference Include="Eto.Forms" Version="2.4.1" />
    <PackageReference Include="Eto.Platform.Gtk3" Version="2.4.1" />'
```

## Specifications

  - Version: 2.4.1
  - Platform(s): linux (ubuntu 18.04) dotnet core 2.1 Gtk3
  - Operating System(s): ubuntu 18.04

**Comment by trampster** [comment]
Never mind, Eto.Platform.Gtk3 is not the correct nuget to use.

The description on that package says this

> This package is deprecated and should not be used in new projects, please use Eto.Platform.Gtk instead. 

After I switched to: Eto.Platform.Gtk it works
