### ISSUE TITLE
WPF: Exception when binding Form.Title in xeto.

### ISSUE THREAD

**Issue by claunia** [picoe/Eto#1376]
## Expected Behavior
Title is binding. It works on GTK+ and Xamarin.Mac

## Actual Behavior
```
System.ArgumentException
  HResult=0x80070057
  Message='' is not a valid value for property 'Title'.
  Source=WindowsBase
  StackTrace:
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at Eto.Wpf.Forms.WpfWindow`3.set_Title(String value)
```

## Steps to Reproduce the Problem

  1. Bind Forms.Title in xeto
  2. Run in WPF

## Specifications

  - Version: 2.4.1
  - Platform(s): WPF
  - Operating System(s): Windows 10

**Comment by Berrysoft** [comment]
Same problem. It works if you manually binding it with code.

**Comment by cwensley** [comment]
Thanks for reporting the problem @claunia and @Berrysoft.  Should now be fixed!
