### ISSUE TITLE
TaskScheduler "The calling thread cannot access this object because a different thread owns it."

### ISSUE THREAD

**Issue by LaraSQP** [picoe/Eto#1498]
The code below work as expected in a WinForms application but throws an exception when using Eto.Forms as shown.

	public partial class MainForm : Form
	{
		TextBox textBox = new TextBox();
		Button button	= new Button();
		readonly TaskScheduler _uiScheduler;

		public MainForm()
		{
			InitializeComponent();

			button.Text = "Start task";
			button.Click += Button_Click;
			_uiScheduler = TaskScheduler.FromCurrentSynchronizationContext();
		}

		private void Button_Click( object sender, System.EventArgs e )
		{
			var cts = new CancellationTokenSource();

			Look( cts, ( msg ) => Report( msg ) );
		}

		private void Look( CancellationTokenSource cts, Action<string> report )
		{
			Task.Factory.StartNew( ( ) =>
			{
				report( "from thread" );
			}, cts.Token );
		}

		private void Report( string msg )
		{
			Task.Factory.StartNew( ( ) =>
			{
				try
				{
					textBox.Text = msg;
				}
				catch( Exception ex )
				{
                   			Console.WriteLine( ex );
				}
			}, CancellationToken.None, TaskCreationOptions.None, _uiScheduler );
		}
	}

Message:
"The calling thread cannot access this object because a different thread owns it."
System.Exception {System.InvalidOperationException}

Stack trace:
System.Windows.Threading.Dispatcher.VerifyAccess()
at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
at Eto.Wpf.Forms.Controls.TextBoxHandler`3.set_Text(String value)
at EtoApp5.MainForm.<>c__DisplayClass6_0.<Report>b__0()

I am new to Eto.

Any clues or suggestions would be much appreciated.

**Comment by LaraSQP** [comment]
Application.Instance.Invoke( () => textBox.Text = msg );

Darn.
