### ISSUE TITLE
Window doens't show when has Icon property set

### ISSUE THREAD

**Issue by lmtr0** [picoe/Eto#1763]
## Expected Behavior
Show A window with Icon

## Actual Behavior
Doesn't show the window but keep runing the app

## Steps to Reproduce the Problem

  1. Create An instance of the Form or Dialog Class
  2. Call the propertie Icon and call a function from load the resoure
       Like This:
       ```CSharp
       Console.Write("Loading  ");
       Icon = Icon.FromResource("MyProj.MyFolder.Logo.png");
       Console.Write("OK");
       ```
  3. See the terminal

## Code that Demonstrates the Problem
```
Form m = new Form();
Console.WriteLine("Loading   ");
m.Icon = Icon.FromResource("Web.wwwroot.CSLogo.png", Assembly.GetExecutingAssembly() );
Console.WriteLine("Loading OK");
m.Show();
```
sometimes it show this error, but i couldn't find out on my own:
```
Marshaling load-changed signal
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Eto.GtkSharp.Forms.Controls.WebViewHandler.get_Url()
   at Eto.GtkSharp.Forms.Controls.WebViewHandler.WebViewHandler_LoadChanged(Object o, SignalArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at Gtk.Application.Run()
   at Eto.GtkSharp.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run()
   at Web.Program.Main(String[] args) in /path/to/repo/projetc/Program.cs:line 13
```

## Specifications

  - Version:
  - Platform(s): Gtk2,
  - Operating System(s):Archlinux 5.7.X

**Comment by cwensley** [comment]
Hey @nacktech, thanks for reporting the issue.  The exception you've shown doesn't actually match the code sample, it appears you're using a WebView in that case.

I just tested with ubuntu 20.04, and it appears to work correctly.  Could you attach a more complete example of what you're doing?  Perhaps there's something else going on there.

**Comment by lmtr0** [comment]
Hey, I managed to resolve the problem, There was an error with my source code

**Comment by lmtr0** [comment]
I forgot to include it on the Project.csproj
