### ISSUE TITLE
Eto stopped working on win 8.1 since 2.5.7

### ISSUE THREAD

**Issue by Mrcubix** [picoe/Eto#1846]
Application: OpenTabletDriver.Installer.Wpf.exe
CoreCLR Version: 5.0.20.51904
.NET Version: 5.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.EntryPointNotFoundException: Unable to find an entry point named 'SetThreadDpiAwarenessContext' in DLL 'User32.dll'.
   at Eto.Win32.SetThreadDpiAwarenessContext(DPI_AWARENESS_CONTEXT dpiContext)
   at Eto.Win32.ScreenHelper.GetLogicalPixelSize(Screen screen)
   at Eto.Win32.GetLogicalPixelSize(Screen screen)
   at Eto.Wpf.Forms.ScreenHandler.GetRealScale()
   at Eto.Wpf.Forms.ScreenHandler.get_RealScale()
   at Eto.Forms.Screen.get_RealScale()
   at Eto.Forms.Screen.get_LogicalPixelSize()
   at Eto.Wpf.Forms.Menu.MenuItemHandler`3.set_Image(Image value)
   at Eto.Forms.ButtonMenuItem.set_Image(Image value)
   at Eto.Forms.ButtonMenuItem..ctor(Command command)
   at Eto.Forms.Command.CreateMenuItem()
   at Eto.Forms.MenuItemCollection.Add(Command command, Int32 order)
   at OpenTabletDriver.Installer.MainForm..ctor() in C:\Work\OpenTabletDriver.Installer\OpenTabletDriver.Installer\MainForm.cs:line 58
   at OpenTabletDriver.Installer.Wpf.MainClass.Main(String[] args) in C:\Work\OpenTabletDriver.Installer\OpenTabletDriver.Installer.Wpf\Program.cs:line 12

Eto stopped working since 2.5.7 and programs that use 2.5.7 and higher version on win 8.1 will crash, causing the .net runtime error above

## Specifications

  - Version:
  - Platform(s): 
  - Operating System(s):

**Comment by cwensley** [comment]
Thanks for reporting the issue!  Yes, I noticed this as well, and this should be fixed in 2.5.9 with #1837
