### ISSUE TITLE
DropDown SelectedValue desynchronizes from UI when DataStore changes

### ISSUE THREAD

**Issue by InfinityGhost** [picoe/Eto#1968]
## Expected Behavior

Switching values is synchronized with the UI as intended when the DataStore is updated.

## Actual Behavior

Switching values from within the UI occasionally desynchronizes the displayed value from SelectedValue when the DataStore is changed. The UI displays the intended selected value, however SelectedValue is internally set to null.

Trying to force the value to be set from null to a different value appears to fail anyway, and no events are invoked when switching in this broken state.

https://user-images.githubusercontent.com/39218853/121764174-e7de8500-cb0f-11eb-8199-bad253fa2f10.mp4

https://user-images.githubusercontent.com/39218853/121764175-e9a84880-cb0f-11eb-978e-cdbc2fc64a42.mp4

## Source

This is the code I discovered this issue with, this is likely the reason for desynchronization, however the behavior is inconsistent so I'm not really sure.

- https://github.com/OpenTabletDriver/OpenTabletDriver/blob/79ffdbdeee9fde74d29ac9bb532778ec8c1391bd/OpenTabletDriver.UX/Controls/TabletSwitcherPanel.cs#L121-L141

## Specifications

  - Version: 2.5.11
  - Platform(s): GTK+ (Reportedly others too, but not tested on my end) 
  - Operating System(s): NixOS 21.11

**Comment by gonX** [comment]
Worth noting that I can reproduce the "blanking out" consistently by simply loading an OTD config from the UI. Using the CLI (`otd load`) does not seem to desynchronize the UI.

Furthermore, trying to interact with the missing gadgets (like tablet area) throws a null reference exception, though I feel it's unrelated:
```
Marshaling motion-notify-event signal
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenTabletDriver.UX.Controls.Output.Area.AreaDisplay.OnMouseMove(MouseEventArgs e) in /home/gonx/.cache/yay/opentabletdriver-git/src/OpenTabletDriver/OpenTabletDriver.UX/Controls/Output/Area/AreaDisplay.cs:line 299
   at Eto.Forms.Control.Callback.OnMouseMove(Control widget, MouseEventArgs e)
   at Eto.GtkSharp.Forms.GtkControl`3.GtkControlConnector.HandleMotionNotifyEvent(Object o, MotionNotifyEventArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at Eto.GtkSharp.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Form mainForm)
   at OpenTabletDriver.UX.App.Run(String platform, String[] args) in /home/gonx/.cache/yay/opentabletdriver-git/src/OpenTabletDriver/OpenTabletDriver.UX/App.cs:line 57
   at OpenTabletDriver.UX.Gtk.Program.Main(String[] args) in /home/gonx/.cache/yay/opentabletdriver-git/src/OpenTabletDriver/OpenTabletDriver.UX.Gtk/Program.cs:line 10
```

**Comment by cwensley** [comment]
Hey, just looked into this, and it is _probably_ caused by using a linq query for your DataStore, which can change each time it is queried.  Try using `.ToList()` on it like so:

```
this.DataStore = profiles.Where(p => tablets.Any(t => t.Properties.Name == p.Tablet)).ToList();
``` 

As for how it desynchronizes, my guess is that the above query is different at the time you are getting the SelectedValue vs. when you are setting the DataStore.  The value for `SelectedValue` simply executes `DataStore.ElementAt(SelectedIndex)`

Hope this helps!

**Comment by InfinityGhost** [comment]
I managed to resolve this a while back using an ObservableCollection, forgot to close this.

**Comment by cwensley** [comment]
Hey @InfinityGhost, thanks!  I'm glad you got it resolved.
