### ISSUE TITLE
Unhandled ArgumentOutOfRangeException thrown on collection changed

### ISSUE THREAD

**Issue by InfinityGhost** [picoe/Eto#2084]
An unhandled System.ArgumentOutOfRangeException is thrown from within Eto when an implementer of `INotifyCollectionChanged` is frequently updated.

## Exception
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Eto.EnumerableChangedHandler`2.InternalElementAt(Int32 index)
   at Eto.CollectionChangedHandler`2.ElementAt(Int32 index)
   at Eto.GtkSharp.Forms.Controls.GtkEnumerableModel`1.GetValue(TreeIter iter, Int32 col, Value& val)
   at Gtk.TreeModelAdapter.GetValue_cb(IntPtr inst, IntPtr iter, Int32 column, IntPtr value)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at Gtk.TreeModelAdapter.GetValue_cb(IntPtr inst, IntPtr iter, Int32 column, IntPtr value)
   at Gtk.Application.Run()
   at Eto.GtkSharp.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Form mainForm)
   at OpenTabletDriver.UX.App.Run(String platform, String[] args) in /repos/OpenTabletDriver/OpenTabletDriver.UX/App.cs:line 62
   at OpenTabletDriver.UX.Gtk.Program.Main(String[] args) in /repos/OpenTabletDriver/OpenTabletDriver.UX.Gtk/Program.cs:line 10
```

## Steps to Reproduce the Problem

  1. Create GTK application with Eto (appears that this happens in some similar way on WPF as well)
  2. Assign a `GridView<T>` with an `INotifyCollectionChanged` DataStore
  3. Rapidly invoke `CollectionChanged` on that DataStore (maybe even asynchronously? I haven't figured out the root cause myself yet)

## Code that Demonstrates the Problem

- [GridView\<T> implementation](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/OpenTabletDriver.UX/Controls/LogView.cs)
- [DataStore](https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/OpenTabletDriver.UX/Tools/LogDataStore.cs)

## Specifications

  - Version: 2.5.11
  - Platform(s): GTK
  - Operating System(s): NixOS 22.05

**Comment by cwensley** [comment]
Thanks for reporting the issue!  I see that you're using a `ConcurrentQueue`, are you by chance adding items in threads other than the UI thread?  If so, the event would be triggered in that non-UI thread which would cause issues.

Additionally, using an `IEnumerable` as your data store is entirely super duper inefficient for large amounts of items.  You should certainly think about implementing `IList` as well so that items can be looked up by index.

**Comment by InfinityGhost** [comment]
> Thanks for reporting the issue! I see that you're using a `ConcurrentQueue`, are you by chance adding items in threads other than the UI thread? If so, the event would be triggered in that non-UI thread which would cause issues.

Even with it defined as a `Queue<T>` this same exception occurs. All additions to this queue have been synchronized to the UI thread in https://github.com/OpenTabletDriver/OpenTabletDriver/pull/1678, and the same exception still occurs. If I've done something wrong there please let me know.
 
> Additionally, using an `IEnumerable` as your data store is entirely super duper inefficient for large amounts of items. You should certainly think about implementing `IList` as well so that items can be looked up by index.

Have done this in the past with a simple `ToList()` for filtering and resulted in worse performance, however on addition it could be added to a background list (or queue to make it easier to limit size) for improved performance.

**Comment by InfinityGhost** [comment]
I realized later that I completely misinterpreted what you meant, LogDataStore should implement IList<T>. Resolved the issue entirely, thanks!

**Comment by cwensley** [comment]
Hey @InfinityGhost, great to hear it's working!  That is indeed what I meant, sorry for being vague.
