### ISSUE TITLE
Cannot install .vsix file in Visual Studio 2022

### ISSUE THREAD

**Issue by thanhcong2k7** [picoe/Eto#2137]
I have downloaded the .vsix extension package from marketplace.visualstudio.com and tried to install it on Visual Studio 2022, but it  gave me an error. This is the log file:

```
2/7/2022 3:17:20 PM - Microsoft VSIX Installer
2/7/2022 3:17:20 PM - -------------------------------------------
2/7/2022 3:17:20 PM - vsixinstaller.exe version:
2/7/2022 3:17:20 PM - 17.0.5226-preview5
2/7/2022 3:17:20 PM - -------------------------------------------
2/7/2022 3:17:20 PM - Command line parameters:
2/7/2022 3:17:20 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\teamc\Downloads\Eto.Addin.VisualStudio.Windows-2.5.11.vsix
2/7/2022 3:17:20 PM - -------------------------------------------
2/7/2022 3:17:20 PM - Microsoft VSIX Installer
2/7/2022 3:17:20 PM - -------------------------------------------
2/7/2022 3:17:21 PM - Initializing Install...
2/7/2022 3:17:21 PM - Extension Details...
2/7/2022 3:17:21 PM - 	Identifier         : Eto.Addin.VisualStudio
2/7/2022 3:17:21 PM - 	Name               : Eto.Forms Visual Studio Addin
2/7/2022 3:17:21 PM - 	Author             : Curtis Wensley
2/7/2022 3:17:21 PM - 	Version            : 2.5.11
2/7/2022 3:17:21 PM - 	Description        : Eto.Forms Support for Visual Studio.  Eto.Forms is a cross platform GUI framework for desktop and mobile applications in .NET that can target Wpf, WinForms, Direct2D, MonoMac, Xamarin.Mac, Gtk2, and Gtk3 with a single codebase.
2/7/2022 3:17:21 PM - 	Locale             : en-US
2/7/2022 3:17:21 PM - 	MoreInfoURL        : https://github.com/picoe/Eto
2/7/2022 3:17:21 PM - 	InstalledByMSI     : False
2/7/2022 3:17:21 PM - 	SupportedFrameworkVersionRange : [4.7.2,)
2/7/2022 3:17:21 PM - 
2/7/2022 3:17:21 PM - 	SignatureState     : Unsigned
2/7/2022 3:17:21 PM - 	Supported Products : 
2/7/2022 3:17:21 PM - 		Microsoft.VisualStudio.Pro
2/7/2022 3:17:21 PM - 			Version : [16.0,)
2/7/2022 3:17:21 PM - 			ProductArchitecture : x86
2/7/2022 3:17:21 PM - 		Microsoft.VisualStudio.Community
2/7/2022 3:17:21 PM - 			Version : [16.0,)
2/7/2022 3:17:21 PM - 			ProductArchitecture : x86
2/7/2022 3:17:21 PM - 		Microsoft.VisualStudio.Enterprise
2/7/2022 3:17:21 PM - 			Version : [16.0,)
2/7/2022 3:17:21 PM - 			ProductArchitecture : x86
2/7/2022 3:17:21 PM - 
2/7/2022 3:17:21 PM - 	References         : 
2/7/2022 3:17:21 PM - 		-------------------------------------------------------
2/7/2022 3:17:21 PM - 		Identifier   : Microsoft.VisualStudio.MPF.16.0
2/7/2022 3:17:21 PM - 		Name         : Visual Studio MPF 16.0
2/7/2022 3:17:21 PM - 		Version      : [16.0,)
2/7/2022 3:17:21 PM - 		MoreInfoURL  : 
2/7/2022 3:17:21 PM - 		Nested       : No
2/7/2022 3:17:21 PM - 
2/7/2022 3:17:21 PM - 		-------------------------------------------------------
2/7/2022 3:17:21 PM - 		Identifier   : 3B5EAFB3-87E4-4986-8924-D24DF860D894
2/7/2022 3:17:21 PM - 		Name         : Microsoft Visual Studio Template Engine
2/7/2022 3:17:21 PM - 		Version      : [16.4.457.38025,)
2/7/2022 3:17:21 PM - 		MoreInfoURL  : 
2/7/2022 3:17:21 PM - 		Nested       : No
2/7/2022 3:17:21 PM - 
2/7/2022 3:17:21 PM - 	Prerequisites      : 
2/7/2022 3:17:21 PM - 		-------------------------------------------------------
2/7/2022 3:17:21 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2/7/2022 3:17:21 PM - 		Name         : Visual Studio core editor
2/7/2022 3:17:21 PM - 		Version      : [16.0,)
2/7/2022 3:17:21 PM - 
2/7/2022 3:17:21 PM - 		-------------------------------------------------------
2/7/2022 3:17:21 PM - 		Identifier   : Microsoft.NetCore.Component.SDK
2/7/2022 3:17:21 PM - 		Name         : .NET Core 3.1 SDK
2/7/2022 3:17:21 PM - 		Version      : [16.0,)
2/7/2022 3:17:21 PM - 
2/7/2022 3:17:21 PM - 		-------------------------------------------------------
2/7/2022 3:17:21 PM - 		Identifier   : Microsoft.VisualStudio.Component.ManagedDesktop.Prerequisites
2/7/2022 3:17:21 PM - 		Name         : .NET desktop development tools
2/7/2022 3:17:21 PM - 		Version      : [16.0,)
2/7/2022 3:17:21 PM - 
2/7/2022 3:17:21 PM - 		-------------------------------------------------------
2/7/2022 3:17:21 PM - 		Identifier   : Microsoft.Net.Component.4.7.2.TargetingPack
2/7/2022 3:17:21 PM - 		Name         : .NET Framework 4.7.2 targeting pack
2/7/2022 3:17:21 PM - 		Version      : [16.0,)
2/7/2022 3:17:21 PM - 
2/7/2022 3:17:21 PM - Signature Details...
2/7/2022 3:17:21 PM - 	Extension is not signed.
2/7/2022 3:17:21 PM - 
2/7/2022 3:17:21 PM - Searching for applicable products...
2/7/2022 3:17:21 PM - Found installed product - Global Location
2/7/2022 3:17:21 PM - Found installed product - Visual Studio Community 2022
2/7/2022 3:17:21 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```
  - Version: Eto.Addin.VisualStudio.Windows-2.5.11.vsix
  - Platform(s): WinForms on .NET 5.0
  - Operating System(s): Windows 10 Version 21H2 (build 19044.1466)

( Sorry for my bad English :( )

**Comment by ievgen-baida** [comment]
Hi @cwensley, do you have any news about the VS 2022 support for the extension?
