### ISSUE TITLE
[GTK] Non-disposed (Leaking) Cairo.Surface when assigning Application.BadgeLabel

### ISSUE THREAD

**Issue by ghost** [picoe/Eto#2252]
## Expected Behavior
I can assign the `Application.BadgeLabel` property with just a string.

## Actual Behavior
Assigning to the field causes Cairo to produce a warning:
```
Cairo.Surface is leaking, programmer is missing a call to Dispose
Allocated from:
   at System.Environment.get_StackTrace()
   at Cairo.CairoDebug.OnAllocated(IntPtr obj)
   at Cairo.Surface..ctor(IntPtr handle, Boolean owner)
   at Cairo.ImageSurface..ctor(Format format, Int32 width, Int32 height)
   at Eto.GtkSharp.Drawing.GraphicsHandler.CreateFromImage(Bitmap image)
   at Eto.Drawing.Graphics..ctor(Bitmap image)
   at Eto.GtkSharp.Forms.ApplicationHandler.set_BadgeLabel(String value)
   at Eto.Forms.Application.set_BadgeLabel(String value)
   at ************************************************ (My code)
```

## Steps to Reproduce the Problem

  1. Be using the GTK Platform
  2. Create a new `Application` object and assign the `.BadgeLabel` property
  3. ```application = new Application(platform)
			{
					Name = "[Name]",
					ID   = "Main Application",
					UIThreadCheckMode = UIThreadCheckMode.Error,
					BadgeLabel = "[Badge]"
			};
  4. See the above error be printed to the console (stacktrace only appears if `MONO_CAIRO_DEBUG_DISPOSE=1` env variable is set)

## Code that Demonstrates the Problem

Full project on [Github](https://github.com/Ararem/RayTracer/tree/899700eadaf312a4110e632a5daa791cb7d7eae6) - you want `RayTracer.Display.Dev` which I'm currently rewriting
```
application = new Application(platform)
{
		Name = "[Name]",
		ID   = "Main Application",
		UIThreadCheckMode = UIThreadCheckMode.Error,
		BadgeLabel = "[Badge]"
};
```

## Specifications

  - Version: ETO.Forms 2.6.1
  - Platform(s): GTK Confirmer, others untested
  - Operating System(s): POP!_OS 22.04 LTS

## Notes
I think the issue is caused by `Eto.GtkSharp.Forms.ApplicationHandler.BadgeLabel.set` ([source](https://github.com/picoe/Eto/blob/develop/src/Eto.Gtk/Forms/ApplicationHandler.cs#L91=)). The issue is that while the `Graphics` object is disposed, the inner `Bitmap` (and probably the inner-inner `BitmapHandler`) don't get disposed. I propose the following to fix the issue:
Replace
```csharp
using (var graphics = new Graphics(new Bitmap(new BitmapHandler(bmp))))
{
	graphics.Clear();
	DrawBadgeLabel(graphics, new Size(bmp.Width, bmp.Height), badgeLabel);
}
```
With
```csharp
using BitmapHandler bitmapHandler = new(bmp);
using Bitmap bitmap = new (bitmapHandler);
using Graphic graphics = new (bitmap);
graphics.Clear();
DrawBadgeLabel(graphics, new Size(bmp.Width, bmp.Height), badgeLabel);
//Automatically disposed because of using statement
```

**Comment by ghost** [comment]
Have just created the PR for this.
I haven't tested it since I can't get the Eto solution to build :( 
![image](https://user-images.githubusercontent.com/48875125/188254311-fdff7ab5-b69f-4fb0-b4b7-a5742a15fa6c.png)

However it should work fine. I also added some `dispose`'s to `DrawBadgeLabel` just in case that was the issue.
