### ISSUE TITLE
[GTK] Testprogram Crashes during "make sure nothing text stays within element" test

### ISSUE THREAD

**Issue by Miepee** [picoe/Eto#2257]
On the "make sure that the text stays within the elements" test, its possible to crash the test program

## Expected Behavior
It shouldn't crash

## Actual Behavior
The program crashes. 
Stacktrace:
```Process terminated. A callback was made on a garbage collected delegate of type 'GLibSharp!GLib.Timeout+TimeoutHandlerInternal::Invoke'.
   at Eto.GtkSharp.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run()
   at Eto.Test.Gtk.Startup.Main(System.String[])

Thread 1 "dotnet" received signal SIGABRT, Aborted.
0x00007ffff788e36c in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff788e36c in  () at /usr/lib/libc.so.6
#1  0x00007ffff783e838 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff7828535 in abort () at /usr/lib/libc.so.6
#3  0x00007ffff74e45ab in  () at /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.6/libcoreclr.so
#4  0x00007ffff74e44e7 in  () at /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.6/libcoreclr.so
#5  0x00007ffff71e281f in  () at /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.6/libcoreclr.so
#6  0x00007ffff71e343f in  () at /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.6/libcoreclr.so
#7  0x00007ffff71e0939 in  () at /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.6/libcoreclr.so
#8  0x00007fff74968d9b in  () at /usr/lib/libgtk-3.so.0
#9  0x00007fff7496efd1 in  () at /usr/lib/libgtk-3.so.0
#10 0x00007fff74684fd8 in  () at /usr/lib/libgtk-3.so.0
#11 0x00007fff76310fd0 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#12 0x00007fff7633d798 in  () at /usr/lib/libgobject-2.0.so.0
#13 0x00007fff7632e62c in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#14 0x00007fff7632ee74 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#15 0x00007fff74944815 in  () at /usr/lib/libgtk-3.so.0
#16 0x00007fff747e2aa2 in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
#17 0x00007fff74544cc3 in  () at /usr/lib/libgdk-3.so.0
#18 0x00007fff745738d8 in  () at /usr/lib/libgdk-3.so.0
#19 0x00007fff7441fc6b in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#20 0x00007fff74476001 in  () at /usr/lib/libglib-2.0.so.0
#21 0x00007fff7441f1cf in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#22 0x00007fff747d8e2f in gtk_main () at /usr/lib/libgtk-3.so.0
#23 0x00007fff7e913aed in  ()
#24 0x00007fff44016828 in  ()
#25 0x000000000033e440 in  ()
#26 0x00007ffff7679f18 in  () at /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.6/libcoreclr.so
#27 0xffffffffffffffff in  ()
#28 0x0000fffee8fb1b21 in  ()
#29 0x00007fff440008c8 in  ()
#30 0x00007fffffffd060 in  ()
#31 0x00007fff7e913aed in  ()
#32 0x00007fffffffd0e0 in  ()
#33 0x00007fff7e9347d9 in  ()
#34 0x0000fffee8fb1b21 in  ()
#35 0x00007fff44011768 in  ()
#36 0x00007fffffffd4e8 in  ()
#37 0x0000000000000000 in  ()
```

## Steps to Reproduce the Problem

  1. Open the Testing program in GTK/Linux
  2. Go through the test, until you get the big dialog with a lot of elements with a text at the bottom saying whether to check if any text in the elements causes the width to increase
  3. Select the text from the combobox, and try to add to it.

## Specifications
  - Version: 2.7.0
  - Platform(s): Eto.GTK
  - Specs:
Operating System: Arch Linux
KDE Plasma Version: 5.25.3
Graphics Platform: Wayland
GTK Theme: Breeze

**Comment by cwensley** [comment]
What test exactly is this?  "make sure nothing text stays within element" is not a name of a test in Eto.

**Comment by Miepee** [comment]
Sorry for vagueness, but issue does not seem to exist anymore.
