### ISSUE TITLE
ETO Form WebView2

### ISSUE THREAD

**Issue by brandon-solemma** [picoe/Eto#2271]
We have installed the [Nuget Microsoft.Web.WebView2](https://www.nuget.org/packages/Microsoft.Web.WebView2) and have confirmed the _dll_ files are in the project, however we receive the following error.

Also have installed

[Canary](https://www.microsoftedgeinsider.com/en-us/download)
[WebView2 runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section)

## Test Standalone ETO app

```
using System;
using Eto.Drawing;
using Eto.Forms;

namespace StandAloneEto
{

    class Startup
    {
        [STAThread]
        public static void Main(string[] args)
        {
            new Application().Run(MainForm.CreateNew());
        }
    }
    public class MainForm
    {
        public static Dialog CreateNew()
        {

            // controls
            var label = new Label { Text = "Hello in C#!" };
            var webView = new WebView { Height = 600 };
            webView.Url = new Uri("https://www.whatsmybrowser.org/");

            // layout
            var layout = new DynamicLayout
            {
                DefaultSpacing = new Size(5, 5),
                Padding = 10
            };
            layout.Add(label);
            layout.Add(webView);
            layout.AddSpace();


            // create form
            var form = new Dialog
            {
                ClientSize = new Size(1000, 600),
                BackgroundColor = Colors.White,
                Padding = 10,
                Resizable = true,
                Title = "Stand alone Eto",

                Content = layout

            };

            form.ShowModal();
            Environment.Exit(0);
            return form;
        }
    }
}
```

**Error**

```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.Threading.Tasks.Task Microsoft.Web.WebView2.Wpf.WebView2.EnsureCoreWebView2Async(Microsoft.Web.WebView2.Core.CoreWebView2Environment)'.
  Source=Eto.Wpf
  StackTrace:
   at Eto.Wpf.Forms.Controls.WebView2Handler.<OnInitializeWebView2Async>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Eto.Wpf.Forms.Controls.WebView2Handler.OnInitializeWebView2Async()
   at Eto.Wpf.Forms.Controls.WebView2Handler.<InitializeAsync>d__7.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at Eto.Wpf.Forms.DialogHandler.ShowModal()
   at Eto.Forms.Dialog.ShowModal()
   at StandAloneEto.MainForm.CreateNew() in C:\Users\DemiC\Documents\GitHub\WebUIExperiments\StandAloneEto\Program.cs:line 54
   at StandAloneEto.Startup.Main(String[] args) in C:\Users\DemiC\Documents\GitHub\WebUIExperiments\StandAloneEto\Program.cs:line 17
```

**Comment by cwensley** [comment]
What version of the Microsoft.Web.WebView2 nuget have you installed?  Eto currently targets `1.0.1020.30`.  As far as I can tell, MS has no issue issuing later versions that have breaking API changes like this.

**Comment by brandon-solemma** [comment]
In the standalone test we just downgraded to 1.0.1245.22 and it returns Edge. However when we are embedding it in Revit we receive IE11.

**Comment by cwensley** [comment]
Yup, just verified the issue.  I guess I'll have to update Eto's WebView2 nuget package to the latest to resolve this.

Please try the version I referenced.  It should work at least with that.

**Comment by demi-solemma** [comment]
In Revit we are running into this error 

> System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.Web.WebView2.Wpf, Version=1.0.1020.30, Culture=neutral, PublicKeyToken=2a8ab48044d2601e' or one of its dependencies. The system cannot find the file specified.'

at `WebView2Loader.Create()` 

which is probably why WebView is falling back to using webview1. 

This might be an issue with Revit but I'm just wondering if you might know where the issue came from, or have seen something similar.

**Comment by cwensley** [comment]
Okay.. not sure how I can replicate that without some form of test project and access to running it in Revit.  Are you running into the error after downgrading the nuget package to `1.0.1020.30`?  Does Revit include WebView2 assemblies of its own?  if so, what version?

**Comment by demi-solemma** [comment]
yes this is with version `1.0.1020.30`

**Comment by demi-solemma** [comment]
Let me check if revit includes WebView2 ! good point!

**Comment by cwensley** [comment]
You may have to add an assembly resolver to load assemblies from the location that the assembly is located.  I'm not sure how Revit/WebView2 resolves the associated assemblies but if it is dynamic you may need to provide a resolver via the `AppDomain.AssemblyResolve` event

**Comment by demi-solemma** [comment]
nope Revit doesn't have microsoft.web

**Comment by demi-solemma** [comment]
ok thank you! we will try that

**Comment by cwensley** [comment]
Closing as this is not an issue with Eto directly.  If you have some further information on how to replicate the problem please don't hesitate to comment and I'll look into it.
