### ISSUE TITLE
[GTK] Excluding manual tests from the unit test crashs

### ISSUE THREAD

**Issue by Miepee** [picoe/Eto#2422]
## Expected Behavior
no crash

## Actual Behavior
crash
``` 
System.ArgumentNullException: Value cannot be null. (Parameter 'store')
   at Eto.Forms.DataStoreExtensions.GetExpandedRowCount[T](IDataStore`1 store, Int32 index) in /home/narr/Dokumente/gitRepos/Eto/src/Eto/Forms/Controls/DaataStoreExtensions.cs:line 24
   at Eto.GtkSharp.Forms.Controls.TreeGridViewHandler.SetSelectedRows(IEnumerable`1 value) in /home/narr/Dokumente/gitRepos/Eto/src/Eto.Gtk/Forms/Controls/TreeGridViewHandler.cs:line 449
   at Eto.GtkSharp.Forms.Controls.GridHandler`2.UpdateModel() in /home/narr/Dokumente/gitRepos/Eto/src/Eto.Gtk/Forms/Controls/GridHandler.cs:line 105
   at Eto.GtkSharp.Forms.Controls.TreeGridViewHandler.CollectionHandler.RemoveAllItems() in /home/narr/Dokumente/gitRepos/Eto/src/Eto.Gtk/Forms/Controls/TreeGridViewHandler.cs:line 96
   at Eto.CollectionChangedHandler`2.OnUnregisterCollection(EventArgs e) in /home/narr/Dokumente/gitRepos/Eto/src/Eto/CollectionChangedHandler.cs:line 43
   at Eto.CollectionChangedHandler`2.Unregister() in /home/narr/Dokumente/gitRepos/Eto/src/Eto/CollectionChangedHandler.cs:line 81
   at Eto.GtkSharp.Forms.Controls.TreeGridViewHandler.set_DataStore(ITreeGridStore`1 value) in /home/narr/Dokumente/gitRepos/Eto/src/Eto.Gtk/Forms/Controls/TreeGridViewHandler.cs:line 106
   at Eto.Forms.TreeGridView.set_DataStore(ITreeGridStore`1 value) in /home/narr/Dokumente/gitRepos/Eto/src/Eto/Forms/Controls/TreeGridView.cs:line 559
   at Eto.Test.Sections.UnitTestPanel.<>c__DisplayClass85_1.<PopulateTree>b__4() in /home/narr/Dokumente/gitRepos/Eto/test/Eto.Test/Sections/UnitTestPanel.cs:line 1561
   at Eto.GtkSharp.Forms.ApplicationHandler.<>c__DisplayClass20_0.<AsyncInvoke>b__0(Object <p0>, EventArgs <p1>) in /home/narr/Dokumente/gitRepos/Eto/src/Eto.Gtk/Forms/ApplicationHandler.cs:line 162
   at Gtk.Application.InvokeCB.Invoke()
   at GLib.Timeout.TimeoutProxy.Handler()
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at GLib.Timeout.TimeoutProxy.Handler()
   at Gtk.Application.Run()
   at Eto.GtkSharp.Forms.ApplicationHandler.Run() in /home/narr/Dokumente/gitRepos/Eto/src/Eto.Gtk/Forms/ApplicationHandler.cs:line 301
   at Eto.Forms.Application.Run() in /home/narr/Dokumente/gitRepos/Eto/src/Eto/Forms/Application.cs:line 375
   at Eto.Test.Gtk.Startup.Main(String[] args) in /home/narr/Dokumente/gitRepos/Eto/test/Eto.Test.Gtk/Startup.cs:line 17

```

## Steps to Reproduce the Problem

  1. Try to exclude manual tests from eto.test unit tests

## Specifications

  - Version: 2.7.3
  - Platform(s): GTK
  - Operating System(s): Arch Linux

**Comment by Miepee** [comment]
Hmm, I can't reproduce this anymore. Excluding manual tests works now both on Wayland and X11 on 91a4744813108d127ec697e03a74d9c102eecdf5 . So I'll close this for now, if someone has this issue in the future, just reopen it.

**Comment by cwensley** [comment]
Thanks @Miepee, I believe I fixed this recently so I'm glad it is working!
