### ISSUE TITLE
[WPF] Photos won't load with an exception

### ISSUE THREAD

**Issue by Serg-Norseman** [picoe/Eto#2479]
A user of my application constantly encounters errors while working with his photo archive.

Type errors:
           at System.Windows.Media.Imaging.BitmapFrame.Create(Stream bitmapStream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption)
           at Eto.Wpf.Drawing.BitmapHandler.Create(Stream stream)
           at Eto.Drawing.Bitmap..ctor(Stream stream)
...
The bitmap property type is unexpected. (0x88982F8E)

I found the following issue, which seems to be the cause of such errors:
https://github.com/dotnet/wpf/issues/7250

Considering the code in the /src/Eto.Wpf/Drawing/BitmapHandler.cs file (https://github.com/picoe/Eto/blob/390aa407cfa828992e399e8fe4a0c2244f528bb4/src/Eto.Wpf/Drawing/BitmapHandler.cs#L82), this is probably the reason (BitmapCacheOption.OnLoad).

## Specifications

  - Version: 2.7.5
  - Platform(s): WPF, NET6
  - Operating System(s): Windows 10

**Comment by cwensley** [comment]
Hey @Serg-Norseman, thanks for submitting the issue but it appears that this is a problem with WPF, and in general the images being corrupt somehow if I grok the linked issue correctly.  Some form of sample to replicate the issue would be nice if there were anything that could possibly be done in Eto to avoid this issue.  

Using OnLoad just means that it loads the image immediately.  Otherwise it'll load it lazily when needed possibly causing issues anyway.

**Comment by Serg-Norseman** [comment]
In my program, users work with genealogical and historical information. In the process, they scan or photograph documents and photos in various resolutions, sometimes huge DPI. Sometimes, the equipment or, more precisely, the drivers or software of the scanner write image files with metadata that is not standard. Most often, the problem occurs in jpeg and tiff formats.

Regular viewers always open such files. In WinForms, the problem also never occurs. The problem only occurs because in WPF with the BitmapCacheOption.OnLoad option, loading incorrect metadata leads to an exception. Photos in general, I repeat, are always correct and load everywhere.

I cannot just tell users: "Your files are broken, give me others" - because the user opens the file and sees absolutely no problems. To get around this problem, as well as to solve the issue with the lack of rotation, if necessary according to the metadata - I use SixLabors.ImageSharp. As a result, I need to try to open the file via Eto, catch the exception, call ImageSharp, load the photo, resize, rotate, save to cache, and then pass it back to Eto.

Some users have photos hundreds of megabytes in size. In order for this photo to open for viewing in my application using Eto, the program overwrites tens of gigabytes in memory.

You have an unusual option `Eto.Wpf.Forms.ToolBar.ToolItemHandler.DefaultImageSize` that is needed to bypass the problematic place in Wpf. To solve the problem with metadata in photos, you could introduce a similar option: use OnLoad or not. After all, Wpf itself does not use this parameter on resource files.

It's a pity that everything will remain as before.

**Comment by Serg-Norseman** [comment]
> Using OnLoad just means that it loads the image immediately. Otherwise it'll load it lazily when needed possibly causing issues anyway.

I didn't write this off the top of my head. But because when I found the problem on dotnet/wpf#7250 - I searched for Eto in the code and tried to replace the option - the problem stopped occurring.

**Comment by cwensley** [comment]
Hey @Serg-Norseman, I didn't mean to make it sound like nothing would be done regarding this.  What I was asking for is some way to replicate the issue so I can verify any sort of fix or workaround.

Your suggestion of adding a (static property) to the handler to specify the default loading options is not a terrible solution to get around this for your case, even without a sample as it would not change the current behaviour..

**Comment by Serg-Norseman** [comment]
I'll look for a photo, for example, so that I can check something.

Considering the nature of the data that my program deals with and the fact that I'm a private person, not a company, I have a hard practice of deleting those problematic files that users send me to combat bugs. I think I'll find what we need.
