### ISSUE TITLE
TabControl without pages is no instance

### ISSUE THREAD

**Issue by LouNGeR83** [picoe/Eto#298]
Testing on: Win7, Eto 2.0.7 and Eto develop from yesterday, Net4.0.

This may be build like this on purpose, or it really is a bug, I don't know.
Fact is, when a TabControl is created, it isn't seen as an instance by certain classes/methods.
I say certain, because it doesn't seem to be consistent. For example, a TabControl in an application I'm working on was working fine on WPF without any pages in it, but Gtk and WinForms bugged out.

The following example seems to throw an exception on every platform.

    using System;
    using Eto.Forms;
    using Eto.Drawing;

    namespace EtoTest
    {
        class MainClass
        {
            [STAThread]
            public static void Main(string[] args)
            {
                new Application(Eto.Platform.Detect).Run(new TabControlTest());
            }
        }

        class TabControlTest : Form
        {
            public TabControlTest()
            {
                Title = "EtoTest.TabControl";
                Size = new Size(300, 400);

                TabControl tabControl = new TabControl();

                // Uncomment and all is fine
                //tabControl.Pages.Add(new TabPage());

                Content = tabControl;
            }
        }
    }

Stacktrace (WinForms)

    System.ArgumentNullException: Value cannot be null.
    Parameter name: source
      at at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
      at at Eto.WinForms.Forms.WindowsContainer`3.BeforeAddControl(Boolean top)
      at at Eto.WinForms.Forms.WindowsPanel`3.set_Content(Control value)
      at at Eto.Forms.Panel.<>c__DisplayClass5.<set_Content>b__4()
      at at Eto.Forms.Container.SetParent(Control child, Action assign, Control previousChild)
      at at Eto.Forms.Panel.set_Content(Control value)
      at at EtoTest.TabControlTest..ctor() in d:\EtoTest\EtoTest.TabControl\Program.cs:line 28
      at at EtoTest.MainClass.Main(String[] args) in d:\EtoTest\EtoTest.TabControl\Program.cs:line 12

**Comment by cwensley** [comment]
Awesome, thanks for the bug report!  It should now be fixed in the develop branch.
