### ISSUE TITLE
Error: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by oghenez** [picoe/Eto#364]
at MetroFramework.Forms.MetroForm.WndProc(Message& m) in C:\Users\Franky\Downloads\winforms-modernui-master\winforms-modernui-master\MetroFramework\Forms\MetroForm.cs:line 590
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at System.Windows.Forms.Form.DefWndProc(Message& m)
   at System.Windows.Forms.Control.WmWindowPosChanged(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmWindowPosChanged(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at MetroFramework.Forms.MetroForm.WndProc(Message& m) in C:\Users\Franky\Downloads\winforms-modernui-master\winforms-modernui-master\MetroFramework\Forms\MetroForm.cs:line 581
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.SafeNativeMethods.SetWindowPos(HandleRef hWnd, HandleRef hWndInsertAfter, Int32 x, Int32 y, Int32 cx, Int32 cy, Int32 flags)
   at System.Windows.Forms.Control.UpdateStylesCore()
   at System.Windows.Forms.Control.UpdateStyles()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Control.set_Visible(Boolean value)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at MetroFramework.Demo.Program.Main() in C:\Users\Franky\Downloads\winforms-modernui-master\winforms-modernui-master\MetroFramework.Demo\Program.cs:line 16

**Comment by cwensley** [comment]
Thanks for submitting the issue, but this doesn't really give me anything to go on.  Could you put together a sample application that reproduces the issue?

**Comment by oghenez** [comment]
i just downloaded and opened in vs2010 and click run, then the error, i wanted to test the demo that was bundled with the libraries

**Comment by cwensley** [comment]
Hm, I might be mistaken, but from the stack trace it does not look like you are using Eto at all.  Which solution file are you loading up?  Try loading up **Eto - net40.sln** (since you are using vs2010 which doesn't support .net 4.5), and set the **Test > Eto.Test.WinForms** project as the startup project.

**Comment by oghenez** [comment]
sorry,my mistake i posted in the wrong place
