### ISSUE TITLE
[WPF] Transparent window not working

### ISSUE THREAD

**Issue by pinting** [picoe/Eto#758]
I cannot set the window transparent neither with Opacity, nor by using a transparent background color.

**Comment by DanWBR** [comment]
Try applying a style to the Panel in your native library:
            
`Eto.Style.Add<Eto.Forms.Panel>("transparent-form", control =>
{
    var wpfwnd = (System.Windows.Window)control.ControlObject;
    wpfwnd.AllowsTransparency = true;
    wpfwnd.Background = Brushes.Transparent;
});`

**Comment by claunia** [comment]
@DanWBR if you try to set AllowsTransparency in a style you get a nice crash:
```
System.InvalidOperationException: Cannot change AllowsTransparency after a Window has been shown or WindowInteropHelper.EnsureHandle has been called.
  at at System.Windows.Window.CoerceAllowsTransparency(DependencyObject d, Object value)
  at at System.Windows.DependencyObject.ProcessCoerceValue(DependencyProperty dp, PropertyMetadata metadata, EntryIndex& entryIndex, Int32& targetIndex, EffectiveValueEntry& newEntry, EffectiveValueEntry& oldEntry, Object& oldValue, Object baseValue, Object controlValue, CoerceValueCallback coerceValueCallback, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, Boolean skipBaseValueChecks)
  at at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
  at at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
  at at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
  at at System.Windows.Window.set_AllowsTransparency(Boolean value)
  at Cyberia.Client.Wpf.WpfStyle.mainViewHandler(FormHandler widget) in D:\Source\repos\Cyberia\Client\Cyberia.Client.Wpf\WpfStyle.cs:90
  at at Eto.Style.<>c__DisplayClass9_0`1.<Add>b__0(Widget widget)
  at at Eto.Style.OnStyleWidget(Widget widget)
  at at Eto.Widget.OnStyleChanged(EventArgs e)
  at at Eto.Widget.set_Style(String value)
```

@cwensley I confirm setting ANY background brush, transparent or not, in a style in WPF, is completely ignored as of 2.4.1.

**Comment by DanWBR** [comment]
@claunia maybe it must be set before the window is shown, as per exception message?

**Comment by claunia** [comment]
@DanWBR well that's the problem, as setting it must be done in a style, and styles are executed after the fact, the only way to change it is directly in the underlying eto handler.

**Comment by DanWBR** [comment]
@claunia are you sure about that? I set the transparency through a style here (https://github.com/DanWBR/dwsim5/blob/windows/DWSIM.UI.Desktop.WPF/Styling.cs#L41) and it is applied during the InitializeComponent() call => https://github.com/DanWBR/dwsim5/blob/windows/DWSIM.UI.Desktop.Forms/Forms/SplashScreen.eto.cs#L28

It seems to work... at least I got no exceptions.

**Comment by claunia** [comment]
Mmm I did get the exception with the style set in a xaml file maybe that difference makes it behave differently.

**Comment by cwensley** [comment]
@claunia It might make a difference if you set the style before any other property.  Setting some of the other properties might be creating the window handle.

**Comment by claunia** [comment]
@cwensley I will check tomorrow, but being in xaml, maybe that would need to be handled automatically, as refactoring can alphasort the attributes

**Comment by claunia** [comment]
@cwensley confirmed with 2.5.0.0-beta1, the order in which Style is set in the XAML makes a difference between raising that exception or not.
